import Head from 'next/head'
import { HomeContainer, Product } from '../styles/pages/home'
import Image from 'next/image'

import { styled } from '../styles'

import Shirt1 from '../assets/1.png'
import Shirt2 from '../assets/2.png'
import Shirt3 from '../assets/3.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <HomeContainer>
        <Product>
          <Image src={Shirt1} alt='Camisa 1' width={520} height={480}/>

          <footer>
            <strong>Camiseta X</strong>
            <span>R$ 79,90</span>
          </footer>
        </Product>

        <Product>
          <Image src={Shirt2} alt='Camisa 2' width={520} height={480}/>

          <footer>
            <strong>Camiseta X-Cross</strong>
            <span>R$ 99,90</span>
          </footer>
        </Product>
      </HomeContainer>
    </>
  )
}
