import Head from 'next/head'
import { HomeContainer, Product } from '../styles/pages/home'
import Image from 'next/image'

import { styled } from '../styles'

import Shirt1 from '../assets/1.png'
import Shirt2 from '../assets/2.png'
import Shirt3 from '../assets/3.png'

import { useKeenSlider } from 'keen-slider/react'
import 'keen-slider/keen-slider.min.css'

export default function Home() {
  const [sliderRef] = useKeenSlider({
    slides: {
      perView: 3,
      spacing: 48
    }
  })

  return (
    <>
      <Head>
        <title>Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <HomeContainer ref={sliderRef} className='keen-slider'>
        <Product className='keen-slider__slide'>
          <Image src={Shirt1} alt='Camisa 1' width={520} height={480} />

          <footer>
            <strong>Camiseta X</strong>
            <span>R$ 79,90</span>
          </footer>
        </Product>

        <Product className='keen-slider__slide'>
          <Image src={Shirt2} alt='Camisa 2' width={520} height={480} />

          <footer>
            <strong>Camiseta X-Cross</strong>
            <span>R$ 99,90</span>
          </footer>
        </Product>

        <Product className='keen-slider__slide'>
          <Image src={Shirt3} alt='Camisa 3' width={520} height={480} />

          <footer>
            <strong>Camiseta X-Cross 2.0</strong>
            <span>R$ 199,90</span>
          </footer>
        </Product>
      </HomeContainer>
    </>
  )
}
